#PBS -N <job_name>
#PBS -q <queue>
#PBS -P <project>
#PBS -j oe

# ------------------------------------------------------------
# IMPORTANT:
# Request 2 GPUs on 1 node
#
# To change GPU count later:
# ngpus=4  --> request 4 GPUs
# ngpus=8  --> request 8 GPUs
# ------------------------------------------------------------
#PBS -l select=1:ngpus=2

#PBS -l walltime=08:00:00

cd $PBS_O_WORKDIR

echo "===== Job Info ====="
echo "Job ID: $PBS_JOBID"

echo "Running on node:"
hostname
echo

echo "===== GPU Info ====="
nvidia-smi
echo

# ------------------------------------------------------------
# Load Modules
# ------------------------------------------------------------
module load apptainer/1.4.1
module load squashfuse/0.5.2
module load gocryptfs/2.5.0

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
container_path="/path/to/pytorch_26.04.sif"

python_script="/path/to/resnet50_singleNode_DDP.py"

# ------------------------------------------------------------
# Container PyTorch Info
# ------------------------------------------------------------
echo "===== Container PyTorch Info ====="

apptainer exec --nv "$container_path" python -c "
import torch
print('PyTorch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('GPU count:', torch.cuda.device_count())

for i in range(torch.cuda.device_count()):
    print(f'GPU {i}:', torch.cuda.get_device_name(i))
"

echo

# ------------------------------------------------------------
# IMPORTANT:
# Launch DDP with torchrun
#
# --nproc_per_node = number of GPUs/processes
#
# To scale later:
# --nproc_per_node=4
# --nproc_per_node=8
# ------------------------------------------------------------
echo "===== Running Multi-GPU DDP Benchmark ====="

# Calculate a random port for PyTorch - this is the ports don't clash on a shared compute node
MASTER_PORT=$((20000 + ${PBS_JOBID%%.*} % 40000))
export MASTER_PORT

apptainer exec --nv \
--env MASTER_PORT="$MASTER_PORT" \
"$container_path" \
torchrun --nproc_per_node=2 --master_port="$MASTER_PORT" "$python_script"
